import type { Metadata } from 'next';
import './globals.css';
import { Open_Sans, Roboto, Karla } from 'next/font/google';

const openSans = Open_Sans({
  weight: ['300', '400', '500', '600', '700', '800'], // Add all weights
  subsets: ['latin'],
  style: ['normal', 'italic'], // Add italic if needed
  display: 'swap',
  variable: '--font-open-sans',
});

const roboto = Roboto({
  weight: ['300', '400', '500', '100', '700', '900'], // Add all weights
  subsets: ['latin'],
  style: ['normal', 'italic'], // Add italic if needed
  display: 'swap',
  variable: '--font-roboto',
});

const karla = Karla({
  weight: ['300', '400', '500', '600', '700', '800'], // Add all weights
  subsets: ['latin'],
  style: ['normal', 'italic'], // Add italic if needed
  display: 'swap',
  variable: '--font-karla',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${karla.variable} ${openSans.variable} ${roboto.variable} antialiased`}>{children}</body>
    </html>
  );
}
